[package]
name = "ntfs-parser"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
serde.workspace = true
tracing.workspace = true
bytes.workspace = true
byteorder.workspace = true
bitflags.workspace = true
chrono.workspace = true
storage = { path = "../storage" }

[dev-dependencies]
tempfile.workspace = true
test-utils = { path = "../test-utils" }
